# date

work:	experimental-ee-aa--GOOD-fast-simple.html
	@cat experimental-ee-aa--GOOD-fast-simple.html > ./index.html

update:	work

main:	work

all:	main
	@chromium ./index.html


# typical use is 'make work' and occasionally 'make work; make all' to launch chromium
# 'make work' just updates index.html which is what chromium is looking at (only).

# experimental-ee-aa--GOOD-fast-simple.html
# experimental-dd-od+0a-inspect.html
# experiment-aa.html
# experiment-bb.html
# experiment-cc-alternate-0a.html
# experiment-cc-alternate-0a-inspect.html
# experiment-cc-alternate-0d+0a.html
# experiment-cc-alternate-0d+0a-inspect.html
# experiment-cc-alternate-0d.html
# experiment-cc-alternate-0d-inspect.html
# thattharisthis.html
# END.
